brew 'git'
brew 'diff-so-fancy'

tap 'git-friendly/git-friendly'
brew 'git-friendly'

tap 'jesseduffield/lazygit'
brew 'lazygit'

brew 'wget'
brew 'pkg-config'
brew 'bash'
brew 'bash-completion@2'
brew 'zsh'
brew 'zsh-completions'
brew 'z'
brew 'unison'
brew 'colordiff'
brew 'broot'
brew 'p7zip'
brew 'unrar'
brew 'xz'
brew 'openssl'
# brew 'openssl@1.1'
brew 'htop'

cask 'iterm2'
# cask 'hyper'

brew 'ssh-copy-id', link: true
brew 'autossh'
brew 'mosh'
brew 'sshfs'
brew 'mkcert'
brew 'nmap'
brew 'telnet'
brew 'namebench'
brew 'speedtest-cli'
brew 'youtube-dl'
brew 'rtmpdump'
